### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by c71n93** [Miha3009/eo2c#1]
Code generation with command `generate` works fine. But there are some compilation errors and warnings, when I'm trying to use `compile` or `dataize` commands on my machine. 

Example of error:
```
/eo2c/bin/example_build/example.cpp:7:64: error: expected ';' after top level declarator static const std::unordered_map<Tag, int> offset_sumOfTwo_print {
```
Example of warning:
```
/eo2c/bin/example_build/org/eolang/../../object.h:101:19: warning: variadic templates are a C++11 extension [-Wc++11-extensions]
template <typename... Bytes>
```

So I just added `set(CMAKE_CXX_STANDARD 11)` to autogenerated `CMakeList.txt` in the `example_build/` directory and all errors have disappeared. @Miha3009, I think this need to be added automatically.

**Comment by Miha3009** [comment]
Yes, I think so too. Everything works for me because the version matches.
